[package]
name = "bnlc-mod-loader-hook"
version = "0.1.0"
edition = "2021"

[lib]
name = "d3d11"
crate-type = ["cdylib"]

[dependencies]
retour = "0.1"
anyhow = "1"
winapi = { version = "0.3.9", features = ["d3d11"] }
log = "0.4"
env_logger = "0.9.0"

[build-dependencies]
cc = "1.0"
